#[derive(Debug, Clone)]
pub enum Place {
	MediterraneanAve,
	Baltic,
	RailRoad,
	Oriental,
	Vermont,
	Connecticut,
	StCharlesPlace,	
	StatesAvenue,	
	VirginiaAvenue,	
	PennsylvaniaRailroad,	
	StJamesPlace,	
	TennesseeAvenue,	
	NewYorkAvenue,	
	KentuckyAvenue,	
	IndianaAvenue,	
	IllinoisAvenue,	
	AtlanticAvenue,	
	VentnorAvenue,	
	MarvinGardens,	
	PacificAvenue,	
	NorthCarolina,	
	PennsylvaniaAvenue,	
	ParkPlace,	
	Boardwalk,
}
